### 가입
POST http://localhost:8081/superbox-study-jwt/api/auth/signup
Content-Type: application/json

{
  "username": "noname",
  "password": "password",
  "email": "google@google.com"
}

### 인증
POST http://localhost:8081/superbox-study-jwt/api/auth/signin
Content-Type: application/json

{
  "username": "noname",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### 권한 없는 조회
GET http://localhost:8081/superbox-study-jwt/api/test/all
Accept: application/json
Authorization: Bearer {{auth_token}}

### 회원 권한 조회
GET http://localhost:8081/superbox-study-jwt/api/test/member
Accept: application/json
Authorization: Bearer {{auth_token}}


### 관리자 권한 조회
GET http://localhost:8081/superbox-study-jwt/api/test/admin
Accept: application/json
Authorization: Bearer {{auth_token}}

### refresh token 갱신
POST http://localhost:8081/superbox-study-jwt/api/auth/refreshToken
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "memberId": "1",
  "refreshToken": "2e27cd6f-6d63-4873-8609-a6bc5f8766fe"
}

