server:
  port: 8081
  servlet:
    context-path: /superbox-study-oauth

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/superbox


superbox:
  app:
    jwtSecret: superbox-study-springboot-security
    jwtExpirationMs: 36000000
