server:
  port: 8081
  servlet:
    context-path: /superbox-study-oauth

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/study-jwt
#    url: jdbc:h2:mem:dev
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2

# App Properties
superbox:
  app:
    jwtSecret: superbox-study-springboot-security
    jwtExpirationMs: 36000000
